# SPDX-License-Identifier: MIT

[workspace]
resolver = "3"
members = ["pg_otel", "sequencing"]

[workspace.package]
version = "0.0.0"
edition = "2024"

[workspace.dependencies]
atoi = "3.1"
eyre = "0.6.12"
googletest = "*"
opentelemetry = { version = "0.32.0", default-features = false }
opentelemetry-proto = { version = "0.32.0", default-features = false }
pgrx = "0.19.2"
pgrx-tests = "0.19.2"
postgres = "0.19"
prost = "0.14.4"
reqwest = { version = "0.12", features = ["blocking"] }
tiny_http = "0.12"
url = "2.5"

[profile.dev]
panic = "unwind"

[profile.release]
opt-level = 3
lto = "fat"
panic = "unwind"
codegen-units = 1
